[platformio]
src_dir = .
include_dir = lib

[env:vsdsquadronMini]
platform = https://github.com/vsdip/vsdsquadron_pio.git
board = vsdsquadronMini
monitor_speed = 115200
framework = noneos-sdk
build_flags = -I lib
build_src_filter = +<app/> +<lib/>