[platformio]
src_dir = .
include_dir = .

[env:vsdsquadronMini]
platform = https://github.com/vsdip/vsdsquadron_pio.git
board = vsdsquadronMini
monitor_speed = 115200
framework = noneos-sdk

; If your SDK requires a specific framework (like spl or ch32v003fun), uncomment and set it below:
; framework = none
